name = input("Hi, I'm Halley! what is your name?")
fn = input("That is a beautiful name, what is your favorite number?")
dc = input("Awesome! Mine is 21. what is your dream car?")
dcc = float(input("That's mine too! What is the cost of your dream car?"))
loan = int(input( "If you were to take out a loan, how many years would it be for?"))
rate = float(input("what is the annual interest you plan to get for the car?"))
payment = (rate/12 * dcc) / (1 - ( 1 + rate/12) ** -(loan * 12))
print(payment, "This is your monthly payment for your dream car!")